/**
 * Browser half of `dsh-voice-input`, in the harness client-bundle format
 * (`window.__ModuleLoader__.load({ id, factory })`).
 *
 * Registers one microphone button in the composer's tool row. It records with
 * `MediaRecorder`, samples the same stream through an `AnalyserNode` so the
 * user can SEE that audio is arriving, posts the bytes to the host half's
 * route, and inserts the returned transcript into the chat draft for review.
 *
 * The level meter is not decoration. A recording indicator that never moves is
 * indistinguishable from a muted microphone: without it the user has no way to
 * know their words are not being captured until the transcript comes back
 * wrong — or empty.
 *
 * The bundle is plain CommonJS-before-bundling by design: it stays readable and
 * needs no build step, so a git install works without a `prepare` script.
 */
window.__ModuleLoader__.load({
  id: 'dsh-voice-input',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    const React = require('react')
    // --- BEGIN INLINED lib/vad.mjs (generated by tools/inline-vad.mjs) ---
    const vadModule = (() => {
      /**
       * When is the user speaking, and when is the room merely humming?
       *
       * This is the piece that decides where one spoken span ends and the next
       * begins, and everything downstream depends on its answers: a live transcript
       * can only appear early if spans are closed early, and it can only be trusted
       * if spans are closed at SILENCE rather than mid-word. A prefix of a recording
       * that is cut inside a word does not fail loudly — the recognizer invents a
       * plausible ending for it, which is worse, because it reads like something the
       * user said.
       *
       * The hard part is not detecting loudness but knowing what quiet LOOKS like on
       * this machine. A fixed threshold (`rms > 0.1`) is defeated by any constant
       * hum: a fridge, a fan, a laptop under load all sit above it permanently, so
       * speech never stands out and no span ever closes. This module therefore tracks
       * the room's own noise floor and compares against that instead.
       *
       * Pure logic on purpose: no DOM, no timers, no audio objects. The caller feeds
       * it one level per tick — which the composer already computes at 20 Hz for its
       * meter — so the whole decision surface is testable in Node, and the browser
       * half stays a thin adapter over it.
       *
       * @module dsh-voice-input/vad
       */
      
      /** How often the caller reports a level. 50 ms = the composer's meter cadence. */
      const TICK_MS = 50
      
      /** Levels sampled over one baseline window (2 s at 20 Hz). */
      const BASELINE_WINDOW = 40
      
      /**
       * Consecutive loud levels that start a span (~200 ms).
       *
       * Long enough that a keyboard click, a cough, or a door never opens one; short
       * enough that the first syllable is not waiting on it.
       */
      const SPEECH_START_TICKS = 4
      
      /**
       * Consecutive quiet levels that close a span (~500 ms).
       *
       * Natural pauses inside a sentence are shorter than this, so a breath does not
       * end a span; a real pause between instructions is longer, so it does.
       */
      const SILENCE_END_TICKS = 10
      
      /** A span quieter than this is a blip, not speech, and is dropped. */
      const MIN_SPEECH_MS = 300
      
      /**
       * Audio kept from BEFORE the span opened (~400 ms).
       *
       * The detector only knows speech began after it has heard a few loud ticks, by
       * which time the first phoneme is already in the past. Without this the
       * transcript would start mid-word.
       */
      const PREROLL_MS = 400
      
      /** How far above the noise floor speech must rise to count (~+7 dB). */
      const GATE_FACTOR = 2.6
      
      /**
       * How near the floor a level must fall to count as silence again.
       *
       * Set well above the floor rather than just above it. This is the line the room
       * has to drop below before a span can close, and it must clear the room's HUM,
       * not merely its quietest moment — a hum that sits above this threshold is
       * counted as continued speech, no silence ever accumulates, and the span stays
       * open until the user presses stop. Anything speech can cross, this must sit
       * below: speech arrives around 0.02-0.15, an order of magnitude higher.
       */
      const REARM_FACTOR = 1.1
      
      /**
       * A span is closed by force after this long, whatever the levels say (~20 s).
       *
       * Silence detection can be defeated: a room noisy enough to sit above the rearm
       * line, a speaker whose voice never drops far enough between sentences, or a
       * floor estimate that landed below the truth. Without a bound, that is a live
       * view which silently produces nothing for the whole recording — the user talks
       * for a minute and sees no text, with no error and no clue. A forced close costs
       * at most one extra decode and always makes progress.
       */
      const MAX_SPAN_MS = 20_000
      
      /**
       * Levels used for the first measurement, before any adaptive tracking (~1 s).
       *
       * Deliberately long: calibration ticks are the quietest the detector will ever
       * see on a real recording, because the microphone is opened moments earlier and
       * nobody speaks into a button they have just pressed. Seeding from too few of
       * them anchors the floor BELOW the room, and every later measurement then looks
       * like speech.
       */
      const CALIBRATION_TICKS = 20
      
      /** The floor never drops below this, so a muted microphone cannot zero the gate. */
      const FLOOR_FLOOR = 0.0008
      
      /**
       * Where the floor starts, before this room has been measured (~-34 dBFS).
       *
       * It must sit ABOVE a quiet room and BELOW speech, and both bounds matter:
       *
       *   too low   a steady hum counts as speech from the first tick. Speech is what
       *             suppresses floor learning, so the detector then cannot measure the
       *             hum it is mishearing, and the mistake is self-sustaining.
       *   too high  ordinary speech never reaches the gate and no span ever opens.
       *
       * A quiet room reads around 0.0005-0.002 and speech around 0.02-0.15, so the
       * gap between them is wide and this sits in the middle of it. It is a starting
       * point, not the decision rule — one window of real ambience replaces it, in
       * either direction.
       */
      const FLOOR_START = 0.004
      
      /** Absolute ceiling on the floor, so a noisy room cannot gate out real speech. */
      const FLOOR_CEILING = 0.08
      
      /**
       * How uniform a window must be to count as ambience.
       *
       * Tight on purpose. A window is only evidence about the room if nothing in it
       * moved much, and the margin has to be small enough that the natural variation
       * WITHIN speech — a syllable to syllable swing of tens of percent — disqualifies
       * it. Measured against speech that jitters by 16%, a band of 1.6 accepts it and
       * the floor climbs onto the speaker's own voice; the gate then rises above them
       * and every span stays open forever.
       */
      const QUIET_BAND = 1.2
      
      /**
       * Tracks one room's noise floor and reports where speech spans begin and end.
       *
       * Feed it `observe` then `advance` once per tick, in that order, with the level
       * the meter already computed.
       */
      class VoiceActivityDetector {
        /**
         * @param {object} [options] - tuning overrides, mainly for tests.
         * @param {number} [options.tickMs] - length of one tick in milliseconds.
         */
        constructor(options = {}) {
          this.tickMs = options.tickMs ?? TICK_MS
          /** The room's own level, in the same linear RMS units as the meter. */
          this.noiseFloor = FLOOR_START
          /** True once speech is loud enough to have opened a span. */
          this.speaking = false
          /** Levels seen since the current span opened, as an approximate duration. */
          this.speechTicks = 0
          /** True while the opening calibration is still gathering its sample. */
          this.calibrating = true
      
          this._window = new Float64Array(BASELINE_WINDOW)
          this._windowCount = 0
          this._windowNext = 0
          this._calibrationSum = 0
          this._calibrationCount = 0
          this._loudTicks = 0
          this._quietTicks = 0
          this._latest = 0
        }
      
        /** The level at which a span opens. Always above the floor by `GATE_FACTOR`. */
        get gate() {
          return Math.max(this.noiseFloor * GATE_FACTOR, FLOOR_FLOOR * GATE_FACTOR)
        }
      
        /** The level a span must fall back to before its silence count starts. */
        get rearm() {
          return Math.max(this.noiseFloor * REARM_FACTOR, FLOOR_FLOOR * REARM_FACTOR)
        }
      
        /**
         * Record this tick's level and refine the noise floor.
         *
         * The floor is derived from the smallest level in a trailing window rather
         * than from an average: speech raises an average permanently, so an
         * average-based floor drifts up during a long instruction and the gate closes
         * on the speaker. The minimum is untouched by speech, because speech only
         * ever makes the window louder.
         *
         * @param {number} level - this tick's linear RMS level.
         */
        observe(level) {
          const value = Number.isFinite(level) && level > 0 ? level : 0
          this._latest = value
      
          // Seed during the opening ticks, so the gate is meaningful immediately
          // rather than after a full window of speech has already gone by.
          if (this.calibrating) {
            this._calibrationCount += 1
            this._calibrationSum = this._calibrationCount === 1
              ? value
              : Math.min(this._calibrationSum, value)
            if (this._calibrationCount >= CALIBRATION_TICKS) {
              this.calibrating = false
              this._seedFloor(this._calibrationSum)
            }
          }
      
          this._window[this._windowNext] = value
          this._windowNext = (this._windowNext + 1) % BASELINE_WINDOW
          if (this._windowCount < BASELINE_WINDOW) {
            this._windowCount += 1
            return
          }
      
          let quietest = Infinity
          let loudest = 0
          for (let index = 0; index < BASELINE_WINDOW; index += 1) {
            const sample = this._window[index]
            if (sample < quietest) quietest = sample
            if (sample > loudest) loudest = sample
          }
          // A measurement is trusted only when the WHOLE window is ambience: every
          // level in it within `QUIET_BAND` of its quietest. A window containing speech
          // is refused, because its quietest level is a pause between words, and
          // adopting that would teach the detector that the speaker's voice is the room.
          const isPureAmbience = loudest <= quietest * QUIET_BAND
          if (!isPureAmbience) return
          // While a span is open, a measurement may only LOWER the floor. Speech can
          // never lower it, so this cannot be abused by a speaker, and it is the one
          // correction that matters: a floor left too high by an earlier loud room
          // would otherwise hold the gate above the speaker and no span would ever
          // open. Raising it while a span is open is forbidden — the gate is what
          // decides the speaker has stopped, so a gate lifted onto their own voice
          // would never let a span close.
          if (this.speaking) {
            if (quietest < this.noiseFloor) this._seedFloor(quietest)
            return
          }
          this._seedFloor(quietest)
        }
      
        /**
         * Advance the state machine one tick and report a span boundary.
         *
         * @returns {{ type: 'start', prerollMs: number } | { type: 'end', speechMs: number } | null}
         *   `start` when a span opened, `end` when one closed with enough speech to be
         *   worth transcribing, otherwise `null`.
         */
        advance() {
          // No span may open before the room has been measured. Otherwise the very
          // first loud ticks — which arrive while the floor is still its placeholder —
          // open a span against a floor that means nothing, and a span that opens too
          // early also freezes floor learning, so the mistake becomes permanent.
          if (this.calibrating) return null
          // Nothing is decided until the floor has had one full window of the room to
          // correct itself against. Speech cannot be told from a steady hum before
          // then, and a span opened in that window opens against a floor that is still
          // a guess.
          if (this._windowCount < BASELINE_WINDOW) return null
      
          if (this._latest >= this.gate) {
            this._quietTicks = 0
            if (!this.speaking) {
              this._loudTicks += 1
              if (this._loudTicks >= SPEECH_START_TICKS) {
                this.speaking = true
                this._loudTicks = 0
                this.speechTicks = 0
                // The span reached back into the ticks already spent deciding, and the
                // caller is asked for the configured pre-roll regardless — it has the
                // audio buffered either way, and the extra is trimmed at the cut.
                return { type: 'start', prerollMs: Math.max(PREROLL_MS, SPEECH_START_TICKS * this.tickMs) }
              }
            } else {
              this.speechTicks += 1
            }
            return null
          }
      
          this._loudTicks = 0
          if (!this.speaking) return null
      
          // Only ticks that are still loud enough to be speech are counted, so the
          // reported duration is the SPOKEN part. Counting the closing silence too
          // would add `SILENCE_END_TICKS` to every span, which for a short utterance is
          // the difference between clearing the minimum and being discarded as a blip.
          if (this._latest >= this.rearm) {
            this.speechTicks += 1
            // Sound came back, so the pause did not end the span. Without this reset a
            // speaker's own breaths accumulate: a sentence with a few natural pauses
            // would reach the closing threshold and be cut into pieces even though the
            // user never stopped talking.
            this._quietTicks = 0
          } else {
            this._quietTicks += 1
          }
      
          // The forced close is checked HERE, on every tick, and not inside the branch
          // above. It exists for the case where the room NEVER drops far enough — a hum
          // louder than the silence threshold, or a speaker who never quite pauses —
          // and in that case the `>= rearm` branch returns before any later test could
          // run. A backstop that the failure mode skips is not a backstop: the span
          // stayed open, the user talked for a minute, and nothing was ever sent.
          const spanMs = (this.speechTicks + this._quietTicks) * this.tickMs
          if (this._quietTicks < SILENCE_END_TICKS && spanMs < MAX_SPAN_MS) return null
      
          const speechMs = this.speechTicks * this.tickMs
          this.speaking = false
          this._quietTicks = 0
          this.speechTicks = 0
          // Too short to be speech: a click, a cough, or a door. Dropped rather than
          // transcribed, because a lone blip costs a whole decode and returns either
          // nothing or an invention.
          if (speechMs < MIN_SPEECH_MS) return null
          return { type: 'end', speechMs }
        }
      
        /** Current state, for the client's indicator and for tests. */
        snapshot() {
          return {
            noiseFloor: this.noiseFloor,
            gate: this.gate,
            speaking: this.speaking,
            calibrating: this.calibrating,
          }
        }
      
        /**
         * Adopt a measured room level.
         *
         * Asymmetric on purpose. Downward is applied at once, because the room really
         * did get quieter and hearing that promptly is what reopens the gate after a
         * fan switches off. Upward is smoothed and bounded, so a stretch of speech
         * that slipped past the gate cannot ratchet the floor up in one step and
         * deafen the detector to the speaker it is listening to.
         *
         * @param {number} measured - the quietest level of an accepted window.
         */
        _seedFloor(measured) {
          const bounded = Math.min(Math.max(measured, FLOOR_FLOOR), FLOOR_CEILING)
          if (bounded < this.noiseFloor) {
            this.noiseFloor = bounded
            return
          }
          // Above the current floor: converge toward it, but never past the ceiling
          // that keeps a loud room from gating out real speech.
          const blended = this.noiseFloor * 0.7 + bounded * 0.3
          this.noiseFloor = Math.min(blended, FLOOR_CEILING)
        }
      }
      
      /**
       * Absolute-RMS floor used when no adaptive measurement is available yet.
       *
       * Speech at a normal distance sits near 0.02-0.15 linear RMS, so this is the
       * "obviously quiet" line — it is a starting point, never the decision rule.
       */
      const DEFAULT_NOISE_FLOOR = 0.005
      

      return { VoiceActivityDetector, DEFAULT_NOISE_FLOOR, TICK_MS, PREROLL_MS, MIN_SPEECH_MS, SILENCE_END_TICKS, SPEECH_START_TICKS, BASELINE_WINDOW }
    })()
    const { VoiceActivityDetector, DEFAULT_NOISE_FLOOR, TICK_MS, PREROLL_MS, MIN_SPEECH_MS, SILENCE_END_TICKS, SPEECH_START_TICKS, BASELINE_WINDOW } = vadModule
    // --- END INLINED lib/vad.mjs ---

    // --- BEGIN INLINED lib/local-agreement.mjs (generated by tools/inline-vad.mjs) ---
    const localAgreementModule = (() => {
      /**
       * LocalAgreement: turn a stream of full-recording hypotheses into stable text.
       *
       * A batch recogniser applied to a growing recording does not produce a stream of
       * settled words. Each pass re-reads everything it is given, so the tail of every
       * hypothesis is a guess that the next pass may revise — and a draft built from
       * those guesses visibly rewrites itself as the user talks.
       *
       * The established answer, from `whisper_streaming` (Macháček et al., IJCNLP 2023
       * demo), is to show a word only once consecutive hypotheses AGREE on it. The
       * longest common word prefix of the last two hypotheses is confirmed; everything
       * after it is withheld. Confirmed text never changes, so the draft only ever
       * grows, and the tail that would have flickered is simply not shown yet.
       *
       * This is pure logic — no audio, no network, no timers — because it is the part
       * where a mistake is invisible in the UI: text that is merely *different* looks
       * like text that is *wrong*, and neither throws.
       *
       * @module dsh-voice-input/local-agreement
       */

      /**
       * How many consecutive hypotheses must agree before their shared prefix is shown.
       *
       * Two is the reference default (`LocalAgreement-2`) and the value its authors
       * recommend: one hypothesis is a guess, and requiring three costs a full extra
       * pass of latency for a difference nobody can hear.
       */
      const MIN_AGREEMENT = 2

      /**
       * Split a transcript into comparable words.
       *
       * Case and surrounding punctuation are ignored when COMPARING, because the
       * recogniser's punctuation of the same word is not stable between passes, and
       * treating "cache." and "cache" as different words would withhold text that is
       * in fact settled. The original spelling of whichever hypothesis is shown is
       * kept for display.
       *
       * @param {string} text - one hypothesis.
       * @returns {string[]} its words.
       */
      function words(text) {
        return text.trim() === '' ? [] : text.trim().split(/\s+/u)
      }

      /**
       * The key two words must share to count as the same word.
       *
       * @param {string} word - one word.
       * @returns {string} its comparison form.
       */
      function key(word) {
        return word.toLowerCase().replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, '')
      }

      /**
       * Longest common prefix of two hypotheses, in words.
       *
       * @param {string[]} a - earlier hypothesis.
       * @param {string[]} b - later hypothesis.
       * @returns {string[]} the shared leading words, in `a`'s spelling.
       */
      function commonPrefix(a, b) {
        const shared = []
        const limit = Math.min(a.length, b.length)
        for (let index = 0; index < limit; index += 1) {
          if (key(a[index]) !== key(b[index]) || key(a[index]) === '') break
          shared.push(a[index])
        }
        return shared
      }

      /**
       * Accumulates hypotheses and reports what is safe to show.
       *
       * Usage: call {@link LocalAgreement#push} with each full transcript of the audio
       * so far, then render `result.confirmed + result.pending` — or render only
       * `confirmed` for text that will never change.
       */
      class LocalAgreement {
        /**
         * @param {object} [options] - tuning overrides, mainly for tests.
         * @param {number} [options.minAgreement] - hypotheses that must agree.
         */
        constructor(options = {}) {
          this.minAgreement = options.minAgreement ?? MIN_AGREEMENT
          /** Text every recent hypothesis agreed on. Never revised. */
          this.confirmed = ''
          /** The tail of the newest hypothesis, still liable to change. */
          this.pending = ''
          this._history = []
        }

        /**
         * Offer one new hypothesis and learn what is now settled.
         *
         * @param {string} hypothesis - the full transcript of the audio so far.
         * @returns {{ confirmed: string, pending: string, changed: boolean }}
         *   `confirmed` is settled text, `pending` is what the newest pass guessed
         *   beyond it, and `changed` says whether the draft needs rewriting at all.
         */
        push(hypothesis) {
          const next = typeof hypothesis === 'string' ? hypothesis.trim() : ''
          this._history.push(words(next))
          // Only the last `minAgreement` hypotheses can confirm anything, so older ones
          // are dropped: keeping them would grow without bound and could never change
          // an answer.
          if (this._history.length > this.minAgreement) this._history.shift()

          if (this._history.length >= this.minAgreement) {
            let agreed = this._history[0]
            for (const other of this._history.slice(1)) {
              agreed = commonPrefix(agreed, other)
              if (agreed.length === 0) break
            }
            const agreedText = agreed.join(' ')
            // The boundary only ever moves forward. A later pass that agrees on LESS
            // than an earlier one has not un-said anything the user already read; it
            // has merely lost confidence in a word that was already settled, and
            // withdrawing text the user has seen is worse than keeping it.
            if (agreedText.length > this.confirmed.length) this.confirmed = agreedText
            // A confirmation means the next pass starts from a fresh pair, so the
            // history is emptied exactly as the reference implementation does.
            if (agreedText !== '') this._history = [words(next)]
          }

          const confirmedWords = words(this.confirmed)
          const nextWords = words(next)
          this.pending = nextWords.slice(confirmedWords.length).join(' ')
          return {
            confirmed: this.confirmed,
            pending: this.pending,
            changed: true,
          }
        }

        /**
         * The text to show: settled words, then the newest guess beyond them.
         *
         * @returns {string} the displayable transcript.
         */
        text() {
          return [this.confirmed, this.pending].filter((part) => part !== '').join(' ')
        }

        /**
         * Take a final transcript as the whole truth and stop accumulating.
         *
         * The finished recording is transcribed in one pass, which is strictly better
         * information than any hypothesis the stream produced: it saw all the audio at
         * once. Whatever it says replaces everything — confirmed and pending alike —
         * so a word the stream settled on wrongly does not survive.
         *
         * @param {string} finalText - the transcript of the complete recording.
         * @returns {string} that text.
         */
        settle(finalText) {
          const text = typeof finalText === 'string' ? finalText.trim() : ''
          this.confirmed = text
          this.pending = ''
          this._history = []
          return text
        }
      }

      return { LocalAgreement, commonPrefix, MIN_AGREEMENT }
    })()
    const { LocalAgreement, commonPrefix, MIN_AGREEMENT } = localAgreementModule
    // --- END INLINED lib/local-agreement.mjs ---

    /** Host route the browser half posts recordings to; must match engine.mjs. */
    const ROUTE = '/voice-input/transcribe'
    /** Posted the audio captured so far, at each silence, to fill the draft live. */
    const SEGMENT_ROUTE = '/voice-input/segment'
    /** Pinged when recording starts so the model can load while the user speaks. */
    const WARM_ROUTE = '/voice-input/warm'
    const SLOT = 'conversation.input.left'
    const ENTRY_ID = 'voice-input-microphone'

    /**
     * Build marker, shown beside the button while recording.
     *
     * The native window injects this bundle at LAUNCH, so an edit here does not
     * reach a window that is already open. Without a marker, "the fix is not
     * loaded yet" and "the fix does not work" look identical from the outside —
     * and telling those two apart is the whole difficulty.
     */
    const BUILD = '0.4.0+live'

    /** Meter geometry, and how often the analyser is sampled. */
    const METER_BARS = 14
    // 50 ms keeps the meter reading as motion (20 fps) rather than as a series
    // of jumps, at a negligible cost: one analyser read and fourteen spans.
    const METER_INTERVAL_MS = 50
    /** Consecutive near-silent samples before the muted-microphone hint appears. */
    const QUIET_SAMPLES_BEFORE_HINT = 30

    /**
     * How often the recorder hands over a chunk while recording.
     *
     * The live view needs the audio in pieces: a peek can only be posted for
     * audio the browser has already produced, and a single chunk delivered at
     * `stop` is precisely the behaviour that made the draft arrive all at once.
     */
    const CHUNK_MS = 1000

    /**
     * Shortest gap between two live peeks.
     *
     * Each peek decodes everything captured so far, so the cost of a recording
     * grows with the square of its length. This keeps that growth off the
     * critical path: a span that closes while a peek is in flight is remembered
     * and posted when the flight finishes, never dropped.
     */
    /**
     * Audio that must accumulate before a decode is worth asking for (~1 s).
     *
     * The reference streaming implementation ships this as its
     * --min-chunk-size 1.0 default. Below roughly a second a decode has too
     * little context to place a word among its neighbours, so it returns nothing
     * — an empty answer that looks like a broken pipeline rather than a short
     * window.
     */
    const MIN_CHUNK_MS = 1000

    const PEEK_MIN_INTERVAL_MS = 1200

    /**
     * New chunks required before another peek (~2 s of audio).
     *
     * Each peek decodes everything captured so far, so the cost of a recording
     * grows with its length. This is the throttle: enough new audio to be worth a
     * decode, without asking for a decode per chunk.
     */
    /**
     * How long one peek may take before it is abandoned (~8 s).
     *
     * A decode grows with the recording, and a peek that never returns would hold
     * the in-flight guard for the rest of the take, silently freezing the live
     * view after its first slow decode.
     */
    const PEEK_TIMEOUT_MS = 8000

    /** Marks the live transcript inside the draft, and pulses while work is in flight. */
    const CARET = '\u258F'

    const CLASS = {
      root: 'dsh-voice-root',
      button: 'dsh-voice-button',
      meter: 'dsh-voice-meter',
      bar: 'dsh-voice-bar',
      watch: 'dsh-voice-watch',
      note: 'dsh-voice-note',
      hint: 'dsh-voice-hint',
      error: 'dsh-voice-error',
      caret: 'dsh-voice-caret',
    }

    /** One CSS rule, injected with the composer's own stylesheet. */
    const CARET_CSS = `
.dsh-voice-caret {
  display: inline-block;
  width: 0.5em;
  margin-left: 1px;
  color: currentColor;
  opacity: 0.85;
  animation: dsh-voice-caret-pulse 1s ease-in-out infinite;
}
@keyframes dsh-voice-caret-pulse {
  0%, 100% { opacity: 0.15; }
  50% { opacity: 0.95; }
}
`

    const CSS = `
.${CLASS.root} { display: inline-flex; align-items: center; gap: 6px; }
.${CLASS.button} {
  display: inline-flex; align-items: center; justify-content: center;
  width: 26px; height: 26px; padding: 0; border: 0; border-radius: 50%;
  background: transparent; color: inherit; opacity: 0.75; cursor: pointer;
}
.${CLASS.button}:hover:not(:disabled) { opacity: 1; background: color-mix(in srgb, currentColor 12%, transparent); }
.${CLASS.button}:disabled { opacity: 0.35; cursor: default; }
.${CLASS.button}[data-state='recording'], .${CLASS.button}[data-state='transcribing'] { color: #e5484d; opacity: 1; }
.${CLASS.meter} { display: inline-flex; align-items: flex-end; gap: 2px; height: 16px; }
.${CLASS.bar} { width: 2px; border-radius: 1px; background: currentColor; opacity: 0.35; transition: height 60ms linear; }
.${CLASS.meter}[data-live='true'] .${CLASS.bar} { opacity: 0.9; }
.${CLASS.watch} { display: inline-flex; align-items: center; gap: 5px; font-size: 11px; font-variant-numeric: tabular-nums; opacity: 0.8; }
.${CLASS.hint} { font-size: 11px; color: #e5a34d; white-space: nowrap; }
.${CLASS.note} { font-size: 11px; opacity: 0.55; white-space: nowrap; }
.${CLASS.error} { max-width: 320px; overflow: hidden; font-size: 11px; color: #e5484d; text-overflow: ellipsis; white-space: nowrap; }
`

    /** Install this bundle's stylesheet once per page and return its remover. */
    function insertStyles() {
      const tag = document.createElement('style')
      tag.dataset.dshVoiceInput = 'true'
      tag.textContent = CSS + CARET_CSS
      document.head.append(tag)
      return () => { tag.remove() }
    }

    function MicrophoneIcon() {
      return React.createElement('svg', {
        viewBox: '0 0 16 16', width: 16, height: 16, fill: 'none',
        stroke: 'currentColor', strokeWidth: 1.4, strokeLinecap: 'round',
        strokeLinejoin: 'round', 'aria-hidden': true,
      },
        React.createElement('rect', { x: 6, y: 1.5, width: 4, height: 8, rx: 2 }),
        React.createElement('path', { d: 'M3.5 7.5a4.5 4.5 0 0 0 9 0' }),
        React.createElement('path', { d: 'M8 12v2.5' }),
      )
    }

    function StopIcon() {
      return React.createElement('svg', { viewBox: '0 0 16 16', width: 16, height: 16, 'aria-hidden': true },
        React.createElement('rect', { x: 4, y: 4, width: 8, height: 8, rx: 2, fill: 'currentColor' }))
    }

    /** Elapsed recording time as `m:ss`. */
    function elapsedText(ms) {
      const total = Math.floor(Math.max(0, ms) / 1000)
      return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`
    }

    /**
     * Map one RMS amplitude to a visible bar fraction.
     *
     * Speech at a normal distance sits near 0.02–0.15 RMS, so a linear scale
     * would leave the meter almost flat; the square root lifts quiet speech into
     * view while still separating loud from soft.
     *
     * @param {number} rms - root-mean-square amplitude in [0, 1].
     * @returns {number} bar height fraction in [0, 1].
     */
    function levelFraction(rms) {
      const lifted = Math.sqrt(Math.min(1, Math.max(0, rms) * 6))
      return Math.max(0.08, Math.min(1, lifted))
    }

    /** The best container this browser records, preferring Opus in WebM. */
    function pickAudioMimeType() {
      const candidates = ['audio/webm;codecs=opus', 'audio/webm', 'audio/ogg;codecs=opus', 'audio/mp4']
      if (typeof MediaRecorder === 'undefined' || MediaRecorder.isTypeSupported === undefined) return undefined
      for (const candidate of candidates) {
        if (MediaRecorder.isTypeSupported(candidate)) return candidate
      }
      return undefined
    }

    function recordingSupported() {
      return typeof MediaRecorder !== 'undefined'
        && typeof navigator !== 'undefined'
        && navigator.mediaDevices !== undefined
        && typeof navigator.mediaDevices.getUserMedia === 'function'
    }

    /**
     * Remove this recording's live text from the draft, keeping everything else.
     *
     * The search is deliberately anchored on the transcript rather than on the
     * draft layout, because the user may have typed while it was streaming, and a
     * blind "keep the first N characters" would delete what they wrote. The
     * markers the live view added — the caret and the separator — go with it.
     *
     * @param {string} current - the draft as it stands.
     * @param {string} base - the draft captured when recording began.
     * @param {string} liveText - the live transcript that was appended to it.
     * @returns {string} the draft without the live transcript.
     */
    function removeLiveText(current, base, liveText) {
      if (liveText === '') {
        // Nothing was transcribed, so only the caret can be present.
        return current.split(CARET).join('')
      }
      const at = current.lastIndexOf(liveText)
      if (at === -1) return current.split(CARET).join('')
      const before = current.slice(0, at)
      const after = current.slice(at + liveText.length).split(CARET).join('')
      if (before === base) return base + after
      // The base itself carries the transcript: the only case that happens is a
      // draft the user has since edited, and then the tail is still theirs.
      if (before.startsWith(base)) return before + after
      return current.split(CARET).join('')
    }

    /**
     * Apply one host frame to the composer draft.
     *
     * Kept at module scope, and driven only through its `sink`, so the
     * partial-transcript logic is testable without a DOM or a React renderer:
     * `sink.setDraft` receives the complete draft text every time.
     *
     * The transcript is appended AFTER whatever the user had already typed —
     * `streamed.base` is captured once, before streaming starts — so a partial
     * update never rewrites or loses existing draft text.
     *
     * @param {{type: string, stage?: string, text?: string, error?: string, polished?: boolean}} frame
     * @param {{base: string, separator: string, text: string, written: boolean}} streamed
     * @param {{setDraft: (text: string) => void, setState: (state: object) => void}} sink
     */
    function applyFrameToDraft(frame, streamed, sink) {
      if (frame === null || typeof frame !== 'object') return
      if (frame.type === 'status') {
        if (frame.stage === 'loading') sink.setState({ phase: 'transcribing', warming: true })
        return
      }
      if (frame.type === 'partial') {
        const text = typeof frame.text === 'string' ? frame.text : ''
        if (text === '') return
        streamed.text = text
        streamed.written = true
        sink.setDraft(streamed.base + streamed.separator + text)
        return
      }
      if (frame.type === 'final') {
        const text = typeof frame.text === 'string' ? frame.text : ''
        streamed.text = text
        sink.setDraft(streamed.base + streamed.separator + text)
        sink.setState({ phase: 'idle', ...(frame.polished === true ? { note: 'cleaned up' } : {}) })
        return
      }
      if (frame.type === 'error') {
        if (streamed.written) {
          // Keep whatever arrived: a half transcript is still the user's words.
          sink.setState({ phase: 'idle', note: frame.error ?? 'transcription stopped early' })
        } else {
          sink.setState({ phase: 'error', message: frame.error ?? 'transcription failed' })
        }
      }
    }


    /** An audio-graph analyser if this browser can build one, else null. */
    function createAnalyser(stream) {
      const Ctor = globalThis.AudioContext ?? globalThis.webkitAudioContext
      if (Ctor === undefined) return null
      try {
        const audioContext = new Ctor()
        const source = audioContext.createMediaStreamSource(stream)
        const analyser = audioContext.createAnalyser()
        analyser.fftSize = 512
        analyser.smoothingTimeConstant = 0.2
        source.connect(analyser)
        // Deliberately NOT connected to the destination: monitoring the mic
        // through the speakers feeds back.
        return {
          audioContext,
          analyser,
          samples: new Uint8Array(analyser.fftSize),
          close: () => { void audioContext.close().catch(() => {}) },
        }
      } catch (error) {
        console.error('voice-input: level metering unavailable', error)
        return null
      }
    }

    /** Root-mean-square amplitude of one time-domain sample window. */
    function rmsOf(samples) {
      let sum = 0
      for (let index = 0; index < samples.length; index += 1) {
        const centred = (samples[index] - 128) / 128
        sum += centred * centred
      }
      return Math.sqrt(sum / samples.length)
    }

    /**
     * Record one voice instruction, show that audio is arriving, transcribe it
     * on the host, and append the result to the current draft.
     */
    function VoiceMic(props) {
      const actions = props.inputActions
      const draft = props.useInput((state) => state.draft)
      const startLevelLoop = props.startLevelLoop
      const [state, setState] = React.useState({ phase: 'idle' })
      const [levels, setLevels] = React.useState(() => new Array(METER_BARS).fill(0))
      const [elapsed, setElapsed] = React.useState(0)
      const [quiet, setQuiet] = React.useState(false)
      const held = React.useRef({ recorder: null, chunks: [], stream: null, startedAt: 0, voice: null, detector: null })
      /** The live transcript being built while the user speaks, or null when idle. */
      const liveRef = React.useRef(null)
      /** The in-flight transcription request, so unmount or a new take can stop it. */
      const abortRef = React.useRef(null)
      const quietStreak = React.useRef(0)
      /**
       * The loudest level heard since this recording began.
       *
       * The muted-microphone hint is decided from this and nothing else. It used
       * to follow the span detector's opinion of whether the user was speaking,
       * which made it fire whenever the detector was merely unsure — reporting a
       * dead microphone to someone who was talking, which is the one thing this
       * hint must never do. The detector's calibration window alone is a second
       * of guaranteed "not speaking", and it was enough to raise the hint on a
       * perfectly good recording.
       */
      const levelPeak = React.useRef(0)
      /**
       * What the last closed span reported, or null while none has closed yet.
       *
       * Kept in a ref rather than in the note itself because the per-tick status
       * line runs every 50 ms: without a record of "a span has closed", the
       * status line overwrites the peek's result before it can be read, and a
       * working live view becomes indistinguishable from one that never ran.
       */
      const spanNote = React.useRef(null)

      const supported = recordingSupported()

      const releaseStream = () => {
        const stream = held.current.stream
        held.current.stream = null
        if (stream === null) return
        for (const track of stream.getTracks()) track.stop()
      }

      const releaseVoice = () => {
        const voice = held.current.voice
        held.current.voice = null
        if (voice !== null) voice.close()
      }

      React.useEffect(() => () => {
        const recorder = held.current.recorder
        if (recorder !== null && recorder.state !== 'inactive') {
          try {
            recorder.stop()
          } catch (error) {
            console.error('voice-input: stopping the recorder on unmount failed', error)
          }
        }
        const controller = abortRef.current
        if (controller !== null) {
          try {
            controller.abort()
          } catch (error) {
            console.error('voice-input: cancelling the transcription on unmount failed', error)
          }
        }
        liveRef.current = null
        releaseStream()
        releaseVoice()
      }, [])

      // The clock and the meter both need a periodic nudge. React cannot
      // re-render from a bare Date.now() read, and the browser's own timer
      // globals are not the sanctioned surface here, so this uses the timer
      // mixin on the plugin context, disposed automatically with the fiber.
      React.useEffect(() => {
        if (state.phase !== 'recording' || startLevelLoop === undefined) return undefined
        const tick = () => {
          setElapsed(Date.now() - held.current.startedAt)
          const voice = held.current.voice
          if (voice === null) return
          voice.analyser.getByteTimeDomainData(voice.samples)
          const rms = rmsOf(voice.samples)
          const level = levelFraction(rms)
          setLevels((previous) => [...previous.slice(1), level])

          // The room's own loudness decides what counts as quiet. The meter's
          // normalised level cannot answer that — it is a fixed scale — so the
          // detector is fed the raw RMS and measures the floor itself. A fridge,
          // a fan or a laptop under load would permanently defeat any fixed line.
          const detector = held.current.detector
          let note
          if (detector === null) {
            quietStreak.current = level <= 0.1 ? quietStreak.current + 1 : 0
          } else {
            detector.observe(rms)
            const boundary = detector.advance()
            // Whether the user can be heard is a question about the AUDIO, not
            // about the detector: the hint answers "is this microphone dead", and
            // the detector answers "has a spoken span ended". Tying the first to
            // the second made a working microphone look dead whenever the
            // detector was still deciding.
            levelPeak.current = Math.max(levelPeak.current, level)
            quietStreak.current = level > 0.006 ? 0 : quietStreak.current + 1
            // The status line CARRIES the evidence rather than being overwritten by
            // it. This fires every 50 ms, so anything a peek writes here is erased
            // within a frame — which is how a live view could be reporting a fault
            // and still look idle. These facts cannot be erased, because they are
            // recomputed and re-shown on every tick:
            //
            //   chunks    how much audio the recorder has actually handed over
            //   last      how long since the last decode was asked for
            //
            // "0 chunks" after 10 seconds of speech is a recorder that never fired
            // `ondataavailable`, which would explain an idle note with no peek:
            // there is nothing to send, so nothing is ever sent.
            const live = liveRef.current
            const snap = detector.snapshot()
            const sincePeek = live === null ? 0 : Date.now() - live.lastPeekAt
            // How much text has actually reached the draft, which is the only way
            // to tell raw recogniser output from cleaned output. This belongs on a
            // line that is recomputed every tick: a note written once by the write
            // itself is erased within a frame, so the one fact that answers the
            // question was the one fact nobody could read.
            const settled = live === null ? 0 : (live.text ?? '').length
            const pending = live === null ? 0 : (live.pendingText ?? '').length
            note = `listening — floor ${snap.noiseFloor.toFixed(4)} gate ${snap.gate.toFixed(4)}`
              + ` · ${held.current.chunks.length} chunk(s)`
              + ` · ${live !== null && live.inFlight ? 'decoding' : `${Math.round(sincePeek / 100) / 10}s idle`}`
              + ` · draft ${settled}+${pending}`
              + `${snap.speaking ? ' · hearing you' : ''}${snap.calibrating ? ' · calibrating' : ''}`
          }
          if (note !== undefined) setState((previous) => ({ ...previous, note }))
          setQuiet(levelPeak.current <= 0.006 && quietStreak.current >= QUIET_SAMPLES_BEFORE_HINT)
        }
        const dispose = startLevelLoop(tick, METER_INTERVAL_MS)
        return () => { dispose() }
      }, [state.phase, startLevelLoop])

      /**
       * Append `text` to whatever the user already had in the draft.
       *
       * The transcript is built on top of a snapshot taken when recording began,
       * never on the draft as it stands now — because the draft IS where the live
       * transcript is being written. Reading it back would append every peek to
       * the previous one.
       *
       * @param {string} text - the transcript so far.
       * @param {string|null} note - a status note to show beside the button.
       */
      const insertTranscriptFrom = (base, text, note) => {
        if (actions === undefined) {
          setState({ phase: 'error', message: 'The composer input is unavailable in this session.' })
          return
        }
        const separator = base === '' || /\s$/.test(base) ? '' : ' '
        actions.setDraft(base + separator + text)
        setState(note === null ? { phase: 'idle' } : { phase: 'idle', note })
      }

      const insertTranscript = (text, note) => {
        insertTranscriptFrom(typeof draft === 'string' ? draft : '', text, note)
      }

      /**
       * Rebuild the draft from the base snapshot plus the live transcript.
       *
       * Anything the user types while this runs is treated as part of their own
       * draft and is preserved: the live text always lands after it, and the
       * final pass rewrites only the live part (see `finishLive`).
       *
       * @param {boolean} active - whether transcription is still in progress.
       */
      const writeLiveDraft = (active) => {
        const live = liveRef.current
        if (actions === undefined || live === null) return
        // Settled words, then the newest guess beyond them, then the caret where
        // the next word will land. Only the first part is promised: the tail may
        // still be revised, which is why it is not shown until it is not.
        const tail = [live.text, live.pendingText ?? ''].filter((part) => part !== '').join(' ')
        const shown = active ? `${tail}${CARET}` : tail
        const separator = live.base === '' || /\s$/.test(live.base) ? '' : ' '
        actions.setDraft(live.base + separator + shown)
        setState((previous) => ({
          ...previous,
          note: `live view: ${live.text.length} settled, ${(live.pendingText ?? '').length} pending`,
        }))
      }

      /**
       * Close the live view and hand the draft back to the caller.
       *
       * The whole live transcript is removed in one operation, whatever the user
       * typed around it, so the authoritative full-recording pass is what the
       * draft finally contains. Without this the pre-polish text would survive
       * underneath the polished text and be sent twice.
       *
       * @returns {string} the text the user had before this recording began.
       */
      const finishLive = () => {
        const live = liveRef.current
        liveRef.current = null
        if (live === null || actions === undefined) return typeof draft === 'string' ? draft : ''
        const current = typeof draft === 'string' ? draft : ''
        // The draft holds settled words AND the pending tail, so both must go.
        // Withdrawing only the settled part would leave the stream's guesswork
        // underneath the final text, and the user would send it twice.
        const streamed = [live.text, live.pendingText ?? ''].filter((part) => part !== '').join(' ')
        const cleaned = removeLiveText(current, live.base, streamed)
        if (cleaned !== current) actions.setDraft(cleaned)
        return cleaned
      }

      /**
       * Decode the audio captured so far and show it, so the draft fills in while
       * the user is still speaking.
       *
       * Only called when the detector says the room went quiet, which is the one
       * moment a peek can be cut without the recognizer inventing an ending for
       * the half-word the cut landed in.
       */
      /**
       * Ask for a peek, if enough new audio has arrived to be worth decoding.
       *
       * Called every time the recorder hands over a chunk. The whole recording so
       * far is sent each time, and the host returns the transcript of ALL of it —
       * which is why no overlap stitching is needed here. The words are not
       * assembled from fragments that have to be aligned; each answer is a
       * complete reading of the audio, so what the draft shows is always
       * internally consistent, and the final pass over the finished recording has
       * the last word.
       *
       * The cost is that a decode grows with the recording, which is why a peek is
       * only asked for once a couple of seconds of new audio exist. For a voice
       * instruction that is a handful of decodes; for a monologue it is more, and
       * the honest bound on it belongs in the README rather than in silence.
       */
      /**
       * Say what the peek chain is doing, beside the button.
       *
       * Every step of this chain used to fail silently, and a silent step is
       * indistinguishable from a step that never ran — which is what made this
       * take so long to find. The specific question now is where the text is
       * lost: in the chunk reaching the route, in the answer coming back, or in
       * the write. Each link says which one it is.
       *
       * @param {string} what - the step, in the words a reader would use.
       */
      const peekTrace = (what) => {
        setState((previous) => ({ ...previous, note: `PEEK ${what}` }))
      }

      const requestPeek = () => {
        const live = liveRef.current
        // `held` is a REF, so every field lives under `.current`. Reading
        // `held.chunks` directly yields `undefined`, and `undefined.length` throws
        // — inside `ondataavailable`, which has no catch, so the handler died
        // silently on every chunk and the peek never ran. The status line beside
        // it read `held.current.chunks` correctly, which is what made the two
        // disagree: one said 17 chunks, the other never spoke.
        const heldNow = held.current
        if (live === null || heldNow.recorder === null) {
          peekTrace('skipped: not recording')
          return
        }
        if (heldNow.chunks.length === 0) {
          peekTrace('skipped: no audio yet')
          return
        }
        // Wait for about a second of audio, which is the reference
        // implementation's `--min-chunk-size 1.0`. Below that a decode has too
        // little context to return anything useful — the recogniser needs to hear
        // a word's neighbours to place it — and the answer would be empty rather
        // than wrong, which reads like a broken pipeline instead of a short
        // window. One chunk is CHUNK_MS of audio, so this is a duration test, not
        // a count of arbitrary pieces.
        const audioMs = heldNow.chunks.length * CHUNK_MS
        if (audioMs < MIN_CHUNK_MS) {
          peekTrace(`waiting: ${Math.round(audioMs / 100) / 10}s of audio so far`)
          return
        }
        // A floor on the gap as well, so a burst of chunks cannot queue a decode
        // per chunk: each peek re-reads the whole recording.
        if (Date.now() - live.lastPeekAt < PEEK_MIN_INTERVAL_MS) {
          peekTrace(`waiting: ${Math.round(audioMs / 100) / 10}s of audio, ${Math.round((Date.now() - live.lastPeekAt) / 100) / 10}s since the last decode`)
          return
        }
        peekTrace(`sending ${Math.round(audioMs / 100) / 10}s of audio`)
        flushPeek().catch((error) => {
          // A floating promise is what turned a hard ReferenceError into complete
          // silence once already. Failures must land somewhere.
          console.error('voice-input: live peek threw', error)
          peekTrace(`threw: ${error && error.message ? error.message : String(error)}`)
        })
      }

      const flushPeek = async () => {
        // `held` is a REF: every field lives under `.current`. Reading
        // `held.recorder` or `held.chunks` directly yields `undefined`, and the
        // next property access throws. That is the same mistake as the misspelled
        // name that hid here before, one level subtler — the name exists, so
        // nothing warns, and only the value is wrong.
        const live = liveRef.current
        const heldNow = held.current
        if (live === null || heldNow.recorder === null || heldNow.chunks.length === 0) {
          const why = live === null
            ? 'not recording'
            : heldNow.recorder === null ? 'no recorder' : 'no audio captured yet'
          peekTrace(`stopped: ${why}`)
          return
        }
        if (live.inFlight) {
          live.pending = true
          peekTrace('queued: one already in flight')
          return
        }
        const type = heldNow.recorder.mimeType === '' || heldNow.recorder.mimeType === undefined
          ? 'audio/webm'
          : heldNow.recorder.mimeType
        const blob = new Blob(heldNow.chunks.slice(), { type })
        if (blob.size === 0) {
          setState((previous) => ({ ...previous, note: 'live view: empty recording so far' }))
          return
        }
        live.inFlight = true
        live.pending = false
        live.lastPeekAt = Date.now()
        live.chunksAtPeek = heldNow.chunks.length
        peekTrace(`posted ${Math.round(blob.size / 1024)} KB`)
        // A deadline on the peek. Without one, a decode that hangs leaves
        // `inFlight` true for the rest of the recording and every later peek is
        // refused by the guard above — a live view that stops silently updating
        // after its first slow decode, which is indistinguishable from one that
        // never worked.
        const abort = new AbortController()
        const deadline = setTimeout(() => { abort.abort() }, PEEK_TIMEOUT_MS)
        try {
          const response = await fetch(SEGMENT_ROUTE, {
            method: 'POST',
            headers: { 'content-type': 'application/octet-stream' },
            body: blob,
            signal: abort.signal,
          })
          const payload = await response.json().catch(() => ({}))
          // A peek that heard nothing changes nothing: the span may have been a
          // cough, or a word whose beginning lay in the previous span.
          if (payload.ok === true && typeof payload.text === 'string' && payload.text.trim() !== '') {
            // Feed the hypothesis to the agreement filter rather than showing it.
            // The recogniser's tail is a guess it may revise on the next pass, so
            // only the words it has now said twice reach the draft: what the user
            // reads never changes under them.
            const agreed = live.agreement.push(payload.text)
            live.text = agreed.confirmed
            live.pendingText = agreed.pending
            live.written = true
            writeLiveDraft(true)
            peekTrace(`got "${payload.text.trim().length} chars"; settled ${agreed.confirmed.length}, pending ${agreed.pending.length}`)
          } else {
            // NOTHING about a peek may be silent. A reply that carries no text is
            // the most important thing to report: it says the request reached the
            // route and the DECODER found nothing in the audio, which is a
            // different fault from a request that never left.
            const reason = typeof payload.error === 'string' && payload.error !== ''
              ? payload.error
              : `HTTP ${response.status} and no text`
            peekTrace(`reply had no text: ${reason}`)
          }
        } catch (error) {
          console.error('voice-input: live peek failed', error)
          peekTrace(`failed: ${error && error.message ? error.message : String(error)}`)
        } finally {
          clearTimeout(deadline)
          live.inFlight = false
          // The peek has reported; let the per-tick status line come back.
          spanNote.current = null
          if (live.pending && liveRef.current !== null) { flushPeek().catch((error) => { console.error('voice-input: live peek threw', error) }) }
        }
      }

      /** One 'status' | 'partial' | 'final' | 'error' frame from the host. */
      const applyFrame = (frame, streamed) => applyFrameToDraft(frame, streamed, {
        setDraft: (value) => {
          if (actions !== undefined) actions.setDraft(value)
        },
        setState,
      })

      const submitAudio = async (blob) => {
        if (actions === undefined) {
          setState({ phase: 'error', message: 'The composer input is unavailable in this session.' })
          return
        }
        setState({ phase: 'transcribing' })
        if (blob.size === 0) {
          setState({ phase: 'error', message: 'The recording was empty; check the microphone input.' })
          return
        }

        // The live transcript is withdrawn first, in one operation: the final
        // pass is authoritative, and leaving the pre-polish text underneath it
        // would send every word twice — once as the recognizer heard it and once
        // as the cleanup rewrote it.
        const base = finishLive()
        const separator = base === '' || /\s$/.test(base) ? '' : ' '
        const streamed = { base, separator, text: '', written: false }
        const controller = new AbortController()
        abortRef.current = controller

        try {
          const response = await fetch(ROUTE, {
            method: 'POST',
            headers: {
              'content-type': 'application/octet-stream',
              // Ask for progress frames rather than one final object.
              accept: 'application/x-ndjson',
            },
            body: blob,
            signal: controller.signal,
          })

          const streamable = response.body !== null
            && typeof response.body.getReader === 'function'
            && String(response.headers.get('content-type') ?? '').includes('ndjson')

          if (!streamable) {
            // An older host answers with one JSON object; keep working with it.
            let payload = {}
            try {
              payload = await response.json()
            } catch (error) {
              console.error('voice-input: the host answered with no readable body', error)
            }
            if (payload.ok !== true) {
              setState({
                phase: 'error',
                message: typeof payload.error === 'string' ? payload.error : `transcription failed (HTTP ${response.status})`,
              })
              return
            }
            insertTranscriptFrom(base, String(payload.text).trim(), payload.polished === true ? 'cleaned up' : null)
            return
          }

          const reader = response.body.getReader()
          const decoder = new TextDecoder()
          let buffer = ''
          for (;;) {
            const { value, done } = await reader.read()
            if (done) break
            buffer += decoder.decode(value, { stream: true })
            let newline = buffer.indexOf('\n')
            while (newline !== -1) {
              const line = buffer.slice(0, newline).trim()
              buffer = buffer.slice(newline + 1)
              if (line !== '') {
                try {
                  applyFrame(JSON.parse(line), streamed)
                } catch (error) {
                  console.error('voice-input: unreadable frame from the host', error)
                }
              }
              newline = buffer.indexOf('\n')
            }
          }
          // A zero-speech recording ends with an error frame and no draft text.
          if (!streamed.written && streamed.text === '') setState({ phase: 'idle' })
        } catch (error) {
          if (error !== null && error !== undefined && error.name === 'AbortError') {
            // The live text is withdrawn with the request: a cancelled
            // transcription must not leave half-decoded words in the draft.
            finishLive()
            setState({ phase: 'idle', note: 'transcription cancelled' })
            return
          }
          setState({
            phase: 'error',
            message: `Transcription request failed: ${error && error.message ? error.message : String(error)}`,
          })
        } finally {
          if (abortRef.current === controller) abortRef.current = null
          // Backstop: `finishLive` already ran before the request, so this only
          // matters on a path that returned before reaching it.
          if (liveRef.current !== null) finishLive()
        }
      }

      const resetMeter = () => {
        setLevels(new Array(METER_BARS).fill(0))
        setElapsed(0)
        setQuiet(false)
        quietStreak.current = 0
        // Each recording is judged on its own audio: a previous take that was
        // loud must not mask a microphone that has since been muted.
        levelPeak.current = 0
        // And each recording reports its own spans: a note left over from the
        // previous take would suppress this one's status line entirely.
        spanNote.current = null
      }

      const finishRecording = () => {
        const recorder = held.current.recorder
        if (recorder === null || recorder.state === 'inactive') return
        setState({ phase: 'transcribing' })
        try {
          recorder.stop()
        } catch (error) {
          setState({ phase: 'error', message: `Stopping the recorder failed: ${String(error)}` })
        }
      }

      const beginRecording = async () => {
        if (state.phase !== 'idle' && state.phase !== 'error') return
        setState({ phase: 'starting' })
        resetMeter()
        try {
          const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
          const voice = createAnalyser(stream)
          if (voice !== null && voice.audioContext.state === 'suspended') {
            await voice.audioContext.resume().catch(() => {})
          }
          const mimeType = pickAudioMimeType()
          const recorder = new MediaRecorder(stream, mimeType === undefined ? undefined : { mimeType })
          const baseDraft = typeof draft === 'string' ? draft : ''
          held.current = {
            recorder,
            chunks: [],
            stream,
            startedAt: Date.now(),
            voice,
            detector: new VoiceActivityDetector({ tickMs: METER_INTERVAL_MS }),
          }
          liveRef.current = {
            base: baseDraft,
            text: '',
            written: false,
            inFlight: false,
            pending: false,
            lastPeekAt: 0,
            chunksAtPeek: 0,
            // The recogniser re-reads the whole recording on every pass, so each
            // answer revises its own tail. This is what decides which words have
            // stopped moving, so the draft grows instead of rewriting itself.
            agreement: new LocalAgreement(),
          }
          // The diagnostic probe is gone: it answered its question. It wrote a
          // known string to the draft on a timer with no audio, no request and no
          // transcription in the path, and the numbers appeared — so the composer
          // demonstrably accepts text while a recording runs, and every remaining
          // fault is downstream of it. Left in place it would overwrite the live
          // transcript on every recording.
          setState({ phase: 'recording', startedAt: held.current.startedAt, note: 'live view on' })
          // Ask the host to load the model NOW, while the user is still
          // speaking: that turns the model-load cost into time the recording
          // was going to take anyway, so the first transcript comes back
          // without a visible pause.
          try {
            void fetch(WARM_ROUTE, { method: 'POST' }).catch(() => {})
          } catch (error) {
            console.error('voice-input: prewarming the model failed', error)
          }
          recorder.ondataavailable = (event) => {
            if (event.data !== undefined && event.data !== null && event.data.size > 0) {
              held.current.chunks.push(event.data)
              // A TIMER, not a silence decision. The peek used to wait for the span
              // detector to report a pause, which made the live view depend on an
              // estimate of the room: a hum louder than the gate read as endless
              // speech, so no pause was ever found and nothing was ever sent. A
              // window of audio needs to know nothing about the room. The recorder
              // emits one chunk per CHUNK_MS, so this runs on a steady cadence for
              // as long as the user speaks.
              requestPeek()
            }
          }
          recorder.onerror = (event) => {
            const detail = event !== null && event.error !== undefined && event.error !== null ? event.error.name : 'unknown error'
            releaseStream()
            releaseVoice()
            liveRef.current = null
            setState({ phase: 'error', message: `The microphone recorder failed: ${detail}` })
          }
          recorder.onstop = () => {
            releaseStream()
            releaseVoice()
            const chunks = held.current.chunks
            const type = recorder.mimeType === '' || recorder.mimeType === undefined ? 'audio/webm' : recorder.mimeType
              held.current = { recorder: null, chunks: [], stream: null, startedAt: 0, voice: null, detector: null }
            // The full recording is still submitted: it is what the final pass
            // transcribes and polishes, and it is authoritative over every peek.
            void submitAudio(new Blob(chunks, { type }))
          }
          // A timeslice is what makes a live view possible at all: without it the
          // browser hands over a single blob at `stop`, so there is nothing to
          // decode while the user is still speaking.
          recorder.start(CHUNK_MS)
          held.current.startedAt = Date.now()
          setState({ phase: 'recording', startedAt: held.current.startedAt, note: `${BUILD} — live view on` })
        } catch (error) {
          releaseStream()
          releaseVoice()
          const name = error !== null && error !== undefined ? error.name : ''
          const detail = name === 'NotAllowedError'
            ? 'Microphone permission was denied; allow the microphone for this page.'
            : name === 'NotFoundError'
              ? 'No microphone was found on this machine.'
              : `The microphone could not be opened: ${error && error.message ? error.message : String(error)}`
          setState({ phase: 'error', message: detail })
        }
      }

      const phase = state.phase
      const busy = phase === 'starting' || phase === 'transcribing'
      const recording = phase === 'recording'
      const label = recording
        ? 'Stop recording and transcribe'
        : phase === 'transcribing' ? 'Transcribing your recording' : 'Record a voice instruction'

      const children = [
        React.createElement('button', {
          key: 'button',
          type: 'button',
          className: CLASS.button,
          'aria-label': label,
          title: supported ? label : 'Voice input needs a browser with microphone recording support',
          'data-state': phase,
          disabled: !supported || busy,
          onClick: recording ? finishRecording : beginRecording,
        }, recording ? StopIcon() : MicrophoneIcon()),
      ]

      if (recording) {
        // The meter carries the "we can hear you" signal; its own aria-label
        // states the same fact for a screen reader.
        children.push(React.createElement('span', {
          key: 'meter',
          className: CLASS.meter,
          'data-live': quiet ? 'false' : 'true',
          role: 'img',
          'aria-label': quiet ? 'No sound detected' : 'Microphone level',
        }, levels.map((level, index) => React.createElement('span', {
          key: index,
          className: CLASS.bar,
          style: { height: `${Math.round(level * 100)}%` },
        }))))
        children.push(React.createElement('span', { key: 'watch', className: CLASS.watch, role: 'timer' },
          elapsedText(elapsed)))
      }
      if (recording && quiet) {
        children.push(React.createElement('span', { key: 'quiet', className: CLASS.hint, role: 'status' },
          'no sound — check your microphone'))
      }
      if (phase === 'transcribing') {
        children.push(React.createElement('span', {
          key: 'busy', className: CLASS.watch, role: 'status',
        }, state.warming === true ? 'loading the model…' : 'transcribing…'))
      }
      if (phase === 'error') {
        children.push(React.createElement('span', {
          key: 'error', className: CLASS.error, role: 'status', title: state.message,
        }, state.message))
      }
      if (state.note !== undefined && (phase === 'idle' || phase === 'recording' || phase === 'transcribing')) {
        // Shown while the recording is RUNNING, not only when it is over. A
        // failure note that appears after the fact cannot tell the user whether
        // the live view was attempted at all, and that was the whole difficulty
        // in finding out why it did nothing.
        children.push(React.createElement('span', {
          key: 'note', className: CLASS.note, role: 'status',
        }, state.note))
      }

      return React.createElement('div', { className: CLASS.root }, ...children)
    }

    /**
     * The only declared dependency: the slot registry.
     *
     * The target slot itself must NOT be declared here. A slot name is not a
     * service, so declaring `conversation.input.left` leaves this browser entry
     * pending forever and the client boot audit fails the whole page —
     * `slots.inject(…)` below is the mechanism that waits for the slot
     * declaration.
     *
     * `timer` IS a real service (the client runner publishes it during its own
     * startup), and the context Guard refuses `ctx.interval` without the
     * declaration: 'cannot get property "interval" without inject'. Probing it
     * with `ctx.get` cannot work around that — the property read is itself what
     * the Guard refuses, before any undefined check runs.
     */
    const inject = ['slots', 'timer']

    /** Register the microphone button for the life of this plugin fiber. */
    function apply(ctx) {
      const removeStyles = insertStyles()
      ctx.effect(() => removeStyles, 'voice-input styles')
      const slots = ctx.slots
      // The timer helpers are mixed onto the CONTEXT, and a slot component
      // receives no context, so the bound interval helper is captured here and
      // handed down as a prop.
      const startLevelLoop = (callback, delay) => ctx.interval(callback, delay)
      slots.inject(SLOT, () => slots.register(
        { name: SLOT, id: ENTRY_ID, order: 50, label: 'Voice input' },
        (props) => (props.inputActions === undefined || props.useInput === undefined
          ? null
          : React.createElement(VoiceMic, { ...props, startLevelLoop })),
      ))
    }

    module.exports.inject = inject
    module.exports.apply = apply
    module.exports.VoiceMic = VoiceMic
    module.exports.levelFraction = levelFraction
    module.exports.applyFrameToDraft = applyFrameToDraft
    module.exports.removeLiveText = removeLiveText
    return module.exports
  },
})