/**
 * Inline the browser bundle's pure-logic modules into `client.cjs`.
 *
 * The client-module loader resolves a bare package name or `<id>/client`; an
 * arbitrary subpath like `dsh-voice-input/lib/vad.mjs` is not a specifier it
 * answers, so requiring one would throw while the bundle was being evaluated and
 * take the microphone button with it.
 *
 * Each module stays the single source of truth. This runs it through one
 * mechanical transform — strip the `export` keywords, wrap it in an IIFE — and
 * splices the result between that module's BEGIN/END markers in the bundle. A
 * test compares each inlined copy against its module line by line, so the two
 * cannot drift; if they did, the behaviour the tests prove would not be the
 * behaviour the browser runs, which is the worst of both.
 *
 * Usage: node tools/inline-vad.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PACKAGE_DIR = dirname(dirname(fileURLToPath(import.meta.url)))
const CLIENT_PATH = join(PACKAGE_DIR, 'client.cjs')

/**
 * One module to splice in, with the names its IIFE must return.
 *
 * @type {{file: string, exports: string[]}[]}
 */
const MODULES = [
  {
    file: 'lib/vad.mjs',
    exports: [
      'VoiceActivityDetector', 'DEFAULT_NOISE_FLOOR', 'TICK_MS', 'PREROLL_MS',
      'MIN_SPEECH_MS', 'SILENCE_END_TICKS', 'SPEECH_START_TICKS', 'BASELINE_WINDOW',
    ],
  },
  {
    file: 'lib/local-agreement.mjs',
    exports: ['LocalAgreement', 'commonPrefix', 'MIN_AGREEMENT'],
  },
]

/**
 * Turn an ES module into a classic script body.
 * @param {string} source - the module's contents.
 * @returns {string} the same code with its export keywords removed.
 */
function stripExports(source) {
  return source
    .replace(/^export\s+(?=(class|const|function|let|var)\b)/gm, '')
    .replace(/^export\s*\{[^}]*\}\s*$/gm, '')
}

let client = readFileSync(CLIENT_PATH, 'utf8')
let inlinedBytes = 0

for (const { file, exports } of MODULES) {
  const begin = `    // --- BEGIN INLINED ${file} (generated by tools/inline-vad.mjs) ---`
  const end = `    // --- END INLINED ${file} ---`
  const beginAt = client.indexOf(begin)
  const endAt = client.indexOf(end)
  if (beginAt === -1 || endAt === -1 || endAt < beginAt) {
    console.error(`inline-vad: the BEGIN/END markers for ${file} are missing from client.cjs`)
    process.exit(1)
  }

  const source = readFileSync(join(PACKAGE_DIR, file), 'utf8')
  const body = stripExports(source)
    .split('\n')
    .map((line) => (line === '' ? '' : `      ${line}`))
    .join('\n')

  // The IIFE is named after the module, and the names it returns are destructured
  // in one statement, so the spliced block reads like the module it came from.
  const varName = `${file.split('/').pop().replace(/\.mjs$/, '').replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Module`
  const block = [
    begin,
    `    const ${varName} = (() => {`,
    body,
    `      return { ${exports.join(', ')} }`,
    '    })()',
    `    const { ${exports.join(', ')} } = ${varName}`,
    end,
  ].join('\n')

  client = client.slice(0, beginAt) + block + client.slice(endAt + end.length)
  inlinedBytes += source.length
}

writeFileSync(CLIENT_PATH, client)
console.log(`inline-vad: inlined ${inlinedBytes} bytes across ${MODULES.length} module(s) into client.cjs`)
