/**
 * Inline `lib/vad.mjs` into `client.cjs`, so the browser bundle carries the span
 * detector instead of requiring a package subpath.
 *
 * The client-module loader resolves a bare package name or `<id>/client`; an
 * arbitrary subpath like `dsh-voice-input/lib/vad.mjs` is not a specifier it
 * answers, so requiring it would throw while the bundle was being evaluated and
 * take the microphone button with it.
 *
 * The module stays the single source of truth. This runs it through one
 * mechanical transform — strip the `export` keywords, wrap it in an IIFE — and
 * splices the result between the BEGIN/END markers in the bundle. A test
 * asserts the inlined copy matches the module, so the two cannot drift.
 *
 * Usage: node tools/inline-vad.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PACKAGE_DIR = dirname(dirname(fileURLToPath(import.meta.url)))
const VAD_PATH = join(PACKAGE_DIR, 'lib', 'vad.mjs')
const CLIENT_PATH = join(PACKAGE_DIR, 'client.cjs')

const BEGIN = '    // --- BEGIN INLINED lib/vad.mjs (generated by tools/inline-vad.mjs) ---'
const END = '    // --- END INLINED lib/vad.mjs ---'

/**
 * Turn the ES module into a classic script body.
 * @param {string} source - the contents of `lib/vad.mjs`.
 * @returns {string} the same code with its export keywords removed.
 */
function stripExports(source) {
  return source
    // `export class Foo` / `export const bar` / `export function baz`
    .replace(/^export\s+(?=(class|const|function|let|var)\b)/gm, '')
    .replace(/^export\s*\{[^}]*\}\s*$/gm, '')
}

const vad = readFileSync(VAD_PATH, 'utf8')
const client = readFileSync(CLIENT_PATH, 'utf8')

const beginAt = client.indexOf(BEGIN)
const endAt = client.indexOf(END)
if (beginAt === -1 || endAt === -1 || endAt < beginAt) {
  console.error('inline-vad: the BEGIN/END markers are missing from client.cjs')
  process.exit(1)
}

const body = stripExports(vad)
  .split('\n')
  .map((line) => (line === '' ? '' : `      ${line}`))
  .join('\n')

const block = [
  BEGIN,
  '    const vadModule = (() => {',
  body,
  '      return { VoiceActivityDetector, DEFAULT_NOISE_FLOOR, TICK_MS, PREROLL_MS, MIN_SPEECH_MS, SILENCE_END_TICKS, SPEECH_START_TICKS, BASELINE_WINDOW }',
  '    })()',
  '    const { VoiceActivityDetector } = vadModule',
  END,
].join('\n')

const next = client.slice(0, beginAt) + block + client.slice(endAt + END.length)
writeFileSync(CLIENT_PATH, next)
console.log(`inline-vad: inlined ${vad.length} bytes of lib/vad.mjs into client.cjs`)
